# services:
#   php:
#     build:
#       context: ./laravel
#     volumes:
#       - ./laravel:/var/www
#     expose:
#       - "9000"
#     working_dir: /var/www

#   nginx:
#     image: nginx:alpine
#     depends_on:
#       - php
#     ports:
#       - "8000:80"
#     volumes:
#       - ./laravel:/var/www
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

services:
  php:
    build:
      context: ./laravel
    volumes:
      - ./laravel:/var/www
    expose:
      - "9000"
    working_dir: /var/www
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    tty: true

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  mysql_data:
